"""Add course to module relations

Revision ID: 22922d139f08
Revises: 69b139a88427
Create Date: 2026-01-02 14:25:16.740915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22922d139f08'
down_revision: Union[str, Sequence[str], None] = '69b139a88427'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Используем batch mode для SQLite
    with op.batch_alter_table("modules", schema=None) as batch_op:
        batch_op.create_foreign_key(
            "fk_modules_course_id_courses", "courses", ["course_id"], ["id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("modules", schema=None) as batch_op:
        batch_op.drop_constraint("fk_modules_course_id_courses", type_="foreignkey")
    # ### end Alembic commands ###
