"""Add filed in student tasks

Revision ID: 3ae161e101d2
Revises: 3becd51be1fd
Create Date: 2026-03-01 18:18:54.164433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae161e101d2'
down_revision: Union[str, Sequence[str], None] = '3becd51be1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_tasks', sa.Column('is_finished', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_tasks', 'is_finished')
    # ### end Alembic commands ###
