"""Add student tasks

Revision ID: 3becd51be1fd
Revises: 0de889c80715
Create Date: 2026-03-01 15:28:58.119223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3becd51be1fd'
down_revision: Union[str, Sequence[str], None] = '0de889c80715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_tasks',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('assignment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('submission_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_tasks')
    # ### end Alembic commands ###
