"""
Caching infrastructure.

Architecture
------------

Application Service
        │
        ▼
CachedRepository
        │
        ├──────────────► MultiLevelCache
        │                     │
        │                ┌────┴────┐
        │                ▼         ▼
        │           MemoryCache  RedisCache
        │
        ▼
Repository (SQLAlchemy / InMemory)
        │
        ▼
Database

Design principles
-----------------
- Cache implements a generic key-string storage.
- CachedRepository implements the Cache-Aside pattern.
- MultiLevelCache implements a read-through L1/L2 cache.
- L1 is an in-process memory cache.
- L2 is a distributed Redis cache.
- Cache keys are generated by a dedicated CacheKeyBuilder.
- Repository methods invalidate cache entries instead of updating them.
- Entity, collection and pagination caches are independent and use different keys.
"""

from .base import Cache
from .in_memory import InMemoryCache
from .multi_level import MultiLevelCache
from .redis import PrimitiveSerializer, RedisCache, Serializer

__all__ = [
    "Cache",
    "InMemoryCache",
    "MultiLevelCache",
    "PrimitiveSerializer",
    "RedisCache",
    "Serializer",
]
