user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log warn;

    proxy_cache_path
        /var/cache/nginx
        levels=1:2
        keys_zone=cdn_cache:50m
        max_size=10g
        inactive=7d
        use_temp_path=off;

    upstream minio {
        server minio:9000;
        keepalive 32;
    }

    include /etc/nginx/conf.d/*.conf;
}