from typing import Protocol, Self, runtime_checkable


@runtime_checkable
class UnitOfWork(Protocol):

    async def __aenter__(self) -> Self: ...

    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...

    async def commit(self) -> None: ...

    async def rollback(self) -> None: ...

    async def flush(self) -> None: ...
